# syntax=docker/dockerfile:1

ARG NODE_VERSION=18.20.4

FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/app/

COPY package*.json .

RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY . .

EXPOSE 3000

CMD ["npm","run","dev-live"]
