version: "3.8"
services:
  db-server:
    image: mariadb:10.11.7
    container_name: mariadb-server
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: cvp
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: [
        "CMD",
        "healthcheck.sh",
        "--su-mysql",
        "--connect",
        "--innodb_initialized"
      ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
      - ./server/utilities/db/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./server/utilities/db/roundcube.sql:/docker-entrypoint-initdb.d/roundcube.sql
    networks:
      - cvp-network
    secrets:
      - db_root_password
      - db_user
      - db_password
  db-client:
    image: phpmyadmin:latest
    container_name: mariadb-client
    ports: 
      - 8080:80
    environment:
      PMA_HOST: db-server
    networks:
      - cvp-network
  email-server:
    depends_on:
        db-server:
          condition: service_started
    image: mailserver/docker-mailserver:13
    container_name: email-server
    restart: always
    hostname: mail.cvp.com
    domainname: docker.local
    ports:
      - 25:25
      - 143:143
    environment:
     PERMIET_DOCER: network
     ENABLE_IMAP: 1
     ENABLE_CLAMAV: 0
     ENABLE_SPAMASSASSIN: 0
     ENABLE_POSTGREY: 0
     ENABLE_FAIL2BAN: 0
     SPOOF_PROTECTION: 0
    volumes:
      - ./server/utilities/email/postfix-main.cf:/tmp/docker-mailserver/postfix-main.cf
    networks:
      - cvp-network
  email-client:
    depends_on:
          db-server:
            condition: service_started
    image: roundcube/roundcubemail:1.6.6-apache
    container_name: email-client
    restart: always
    ports:
      - 8000:80
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: email-server
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_SERVER: email-server
      ROUNDCUBEMAIL_SMTP_PORT: 25
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: db-server
      ROUNDCUBEMAIL_DB_NAME: roundcubemail
    volumes:
      - ./server/utilities/email/roundcube-config.php:/var/roundcube/config/roundcube-config.php
    networks:
      - cvp-network
    secrets:
      - roundcube_db_password
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: on-failure
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-cache:/data
    networks:
      - cvp-network
  server:
    depends_on:
      db-server:
        condition: service_started
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cvp-server
    ports:
      - 5000:5000
    volumes:
      - "./server:/usr/src/app/server"
    env_file:
      - .env
    networks:
      - cvp-network
  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: cvp-client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./client/src:/usr/src/app/src"
      - "./client/public:/usr/src/app/public"
      - "./client/tests:/usr/src/app/tests"
      - "./client/index.html:/usr/src/app/index.html"
      - "./client/package-lock.json:/usr/src/app/package-lock.json"
      - "./client/package.json:/usr/src/app/package.json"
      - "./client/tsconfig.json:/usr/src/app/tsconfig.json"
      - "./client/tsconfig.node.json:/usr/src/app/tsconfig.node.json"
      - "./client/vite.config.ts:/usr/src/app/vite.config.ts"
    networks:
      - cvp-network
secrets:
  db_root_password:
    file: ./server/utilities/db/db_root_password.txt
  db_user:
    file: ./server/utilities/db/db_user.txt
  db_password:
    file: ./server/utilities/db/db_password.txt
  roundcube_db_password:
    file: ./server/utilities/db/db_root_password.txt
volumes:
  db-data:
    driver: local
  redis-cache:
    driver: local
networks:
  cvp-network:
    name: cvp-network
