name: deployment
on:
  push:
    branches: ["**"]
  workflow_dispatch:
jobs:
  server-test:
    strategy:
      matrix:
        os: [ubuntu,windows]
        node-version: [16.x,18.x,20.x]
    name: ${{ matrix.os }} - ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Jest
        run: npm test
  client-test:
    strategy:
      matrix:
        os: [ubuntu,windows]
        node-version: [18.x,20.x]
    name: ${{ matrix.os }} - ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: './client'
        run: npm ci
      - name: Run Vitest
        working-directory: './client'
        run: npm test 
  deploy:
    runs-on: ubuntu-latest
    needs: [server-test, client-test]
    steps:
      - name: Deploy to cPanel
        uses: pinkasey/cpanel-deploy-action@v1.2.0
        with:
          hostname: "${{ secrets.CPANEL_HOSTNAME }}"
          repository_root: "${{ secrets.CPANEL_REPO_ROOT }}"
          branch: "${{ github.ref_name }}"
          cpanel_username: "${{ secrets.CPANEL_USERNAME }}"
          cpanel_token: "${{ secrets.CPANEL_TOKEN }}"