name: CI
on:
  push:
    branches: ["main", "react"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        uses: pinkasey/cpanel-deploy-action@v1.2.0
        with:
          hostname: "${{ secrets.CPANEL_HOSTNAME }}"
          repository_root: "${{ secrets.CPANEL_REPO_ROOT }}"
          branch: "$GITHUB_BRANCH"
          cpanel_username: "${{ secrets.CPANEL_USERNAME }}"
          cpanel_token: "${{ secrets.CPANEL_TOKEN }}"
env:
    GITHUB_BRANCH: ${{ github.ref_name }}